### ISSUE TITLE
Missing AP_AESTERM message

### ISSUE THREAD

**Issue by xdelatour** [freemint/tos.hyp#104]
In the message list (gem/aes/evnt_/messages/messages.u), the message AP_AESTERM (52) from N.AES is missing.

**Comment by th-otto** [comment]
Do you have any description what it does? Or can ppoint me to some N.AES documentation?

**Comment by xdelatour** [comment]
I found only this description in the N.AES documentation : [Systemshutdown](http://tho-otto.de/hypview/hypview.cgi?url=%2Fhyp%2Fn_aes.hyp&charset=UTF-8&index=112)
