### ISSUE TITLE
Sysconf(): new values (8 and 9)

### ISSUE THREAD

**Issue by xdelatour** [freemint/tos.hyp#110]
Since https://github.com/freemint/freemint/commit/5753b34bf677c92f65eaa96f7c308f2866a5ce7b there are two new values for parameter *n*  in [Sysconf](https://github.com/freemint/tos.hyp/blob/master/gemdos/system/sysconf.ui)
- 8 Password buffer size
- 9 Group buffer size

**Comment by xdelatour** [comment]
[sysconf.ui.patch.txt](https://github.com/freemint/tos.hyp/files/9794250/sysconf.ui.patch.txt)
(with an attempt to translate into German)

**Comment by mikrosk** [comment]
Nice, thank you.
