### ISSUE TITLE
Ssystem(): new modes

### ISSUE THREAD

**Issue by xdelatour** [freemint/tos.hyp#111]
Some names in tos.hyp are not the same in file headers:
- S_FORCEFASTLOAD(0x0013): S_FASTLOAD
- S_CAD(0x0019): S_CTRLALTDEL
- S_CLOCKMODE(0x0064): S_CLOCKUTC
- S_DEBUGDEV(0x03e9): S_DEBUGDEVICE

5 additional modes are available:
- S_DELCOOKIE(0x001a): Removes a tag ID specified by arg1 from the cookie jar. If there is no slot with the specified tag ID, no action is performed and EINVAL is returned instead. S_DELCOOKIE requires root euid, EPERM is returned otherwise and no action is performed.
- S_LOADKBD(0x001b): Load the keyboard table into memory. arg1 specify the address of the complete path to the keyboard table or NULL. If path is NULL the default path of `<sysdir>/keyboard.tbl` is used. S_LOADKBD requires root euid, EPERM is returned otherwise and no action is performed. Returns a negative GEMDOS error-code if it fails. On success this call returns 0 and _AKP and _ISO cookies are updated.
- S_SETEXC(0x001c): Allow Setexc(). Valid arg1 values are as follows:
  - -1 return the current setting
  - 0 deny all (only kernel-processes may change sys-vectors)
  - 1 deny trap-changes (numbers 0-15)
  - 2 allow all (default)
S_SETEXC requires root euid, EPERM is returned otherwise and no action is performed. Returns EBADARG if arg1 is greater than 2, or 0 on success.
- S_GETBOOTLOG(0x001d): Inquires the file path of bootlog file. arg1 and arg2 specify the address and length in bytes, respectively, of a memory buffer where a NULL-terminated ASCII string will be written identifying the full name of the bootlog file. If the memory buffer is not long enough to hold the entire string, the string is truncated down to the buffer size. S_GETBOOTLOG requires root euid, EPERM is returned otherwise and no action is performed. Returns EBADARG if arg1 is null or if arg2 is 0. On success this call returns 0.
- S_DEBUGKMTRACE(0x044c): (as far as I understand) Dump out kmalloc'ed blocks with size and caller (debug kernel). arg1 specifiy the address of the kmalloc'ed block to check and arg2 specify the memory buffer where the dump will be written. S_DEBUGKMTRACE requires root euid, EPERM is returned otherwise and no action is performed. Returns ENOENT if it fails. On success this call returns 0.

**Comment by mikrosk** [comment]
Indeed. At least https://github.com/freemint/freemint/blob/master/doc/programmer/newcall.html/ssystem.html mentions them all (too bad that those html files are not exported/shown somewhere...)

**Comment by mikrosk** [comment]
I've made a simple change in the freemint repository so the new syscalls are at least _somehow_ visible: https://freemint.github.io/freemint. I have also added the link in https://github.com/freemint/freemint/wiki/Category_New_MiNT_system_calls.

But yeah, having them in tos.hyp would be also nice, so not closing.

**Comment by xdelatour** [comment]
> But yeah, having them in tos.hyp would be also nice, so not closing.

Done!
[ssystem.ui.patch.txt](https://github.com/freemint/tos.hyp/files/11033543/ssystem.ui.patch.txt)
