### ISSUE TITLE
Dcreate(): pathname should not contain a trailing backslash

### ISSUE THREAD

**Issue by xdelatour** [freemint/tos.hyp#115]
Tested on Steem SSE + TOS 1.02fr, Dcreate() with a pathname ending with a backslash failed (-34).

This behaviour is mentioned in Atari Compendium but missing from Tos.hyp and original docs from Atari (Atari GEMDOS Reference Manual April 4, 1986)

On MiNT, the specified directory is successfully created.

**Comment by mikrosk** [comment]
Fixed in https://github.com/freemint/tos.hyp/commit/4dc77b980056435e9352db0f2ef2a660c84f91d8.

Thanks for reporting.
