### ISSUE TITLE
Redirect of toshyp.atari.org to freemint.github.io/tos.hyp?

### ISSUE THREAD

**Issue by mikrosk** [freemint/tos.hyp#168]
I've asked atari.org guys whether this would be possible and the answer is that it is, it's really just an update on their side.

@pulsar122 do you see an issue with that? It's true that https://toshyp.atari.org/en/index.html mentions the updated version but:
- https://toshyp.atari.org doesn't
- when landing on e.g. https://toshyp.atari.org/en/005010.html#Cnecin it's not visible, i.e. random reader can get outdated information (see next point)
- google often prefers atari.org version over ours

**Comment by pulsar122** [comment]
The only thing I always thought is that the old links will no longer work, because the names of some pages have changed.

But I have no problem with the redirection. But give me a little more time, I still have to do a few things.

I have changed the page https://toshyp.atari.org/.

**Comment by pulsar122** [comment]
I have done my work. So they can make the redirect.

**Comment by mikrosk** [comment]
https://toshyp.atari.org now redirects to https://freemint.github.io/tos.hyp.

Thanks Gerhard!

**Comment by mikrosk** [comment]
> The only thing I always thought is that the old links will no longer work, because the names of some pages have changed.

Oh man, *now* I see what you meant there. Indeed e.g. https://toshyp.atari.org/en/008009.html definitely doesn't link to a proper place anymore (which should link to https://freemint.github.io/tos.hyp/en/wind.html).

@th-otto did you change something in udo or tos.hyp (or both) which caused such a drastic change?

**Comment by mikrosk** [comment]
Just for the context, try https://www.google.com/search?q=wind_set+atari and you see why it is important...

**Comment by pulsar122** [comment]
It is a change in tos.hyp. Instead of UDO give an HTML page a name. You can use the command !html_name to give a name you want. This was make there 
https://github.com/freemint/tos.hyp/commit/d0c3d33a54e816fb8e9cd3378bbb40e0e1e46e74

This was not wrong, but make now a little bit of trouble.

**Comment by th-otto** [comment]
The reason why this was done is simple: if you don't do this, you will get html names like "008009.html", which just depend on the node structure, and will change anytime you insert a new node somewhere to document another function. So that google link will suddenly not link to wind_set anymore, but to something else.

I don't know how long google caches hits, but shouldn't the above example just disappear in a while?

**Comment by mikrosk** [comment]
Oh my, this is just bad and worse. :) Okay, perhaps we just wait for google to movie that those links are dead.
