### ISSUE TITLE
Add additional information to menu_popup()

### ISSUE THREAD

**Issue by lpgb** [freemint/tos.hyp#169]
https://freemint.github.io/tos.hyp/en/menu.html#menu_popup
I'd like to suggest menu_popup() availability be updated with more precise information. It's based on tests with Atari's AES 4.1 and Atari's AES4DEMO program and SUBMENU.CPX as well as tests with N.AES. Below this line:
_____________
Availability: 	This function is available only with AES versions 3.30 and above. 

If _mn_scroll_ of [MENU](https://freemint.github.io/tos.hyp/en/aes_structures.html#MENU) is set to 0 when menu_popup is called, a non-scrollable popup menu will be displayed.

If _mn_scroll_ of [MENU](https://freemint.github.io/tos.hyp/en/aes_structures.html#MENU) is set to >0 when menu_popup is called, a scrolling popup menu will be displayed; _height_ of [MN_SET](https://freemint.github.io/tos.hyp/en/aes_structures.html#MN_SET) determines it's height in items (note that Atari's AES implements up/down arrows within the popup for scrolling to maintain the same look and feel of dropdown menus as they can be attached to menubar items, note that NAES mimics this exact behavior) See also [menu_settings](https://freemint.github.io/tos.hyp/en/menu.html#menu_settings).

As of AES version 4.1, if _mn_scroll_ of [MENU](https://freemint.github.io/tos.hyp/en/aes_structures.html#MENU) is set to -1 when menu_popup is called, a dropdown list box instead of a popup menu will be displayed; this will have a scroll bar if eight entries or more exist.

**Comment by mikrosk** [comment]
Looks good to me. @th-otto @gokmase @skaftetryne any objections?

**Comment by th-otto** [comment]
I saw you already updated the comments in the menu structure, but not yet the description of menu_popup(). Are you going to update that, too? (remember that there is also a german description)

**Comment by mikrosk** [comment]
That was Lonny's patch, so yes, the idea is to commit this one as a follow-up. However I'm afraid I can't help with the german part.

**Comment by lpgb** [comment]
If anyone wants the items used for testing I can attach them.

**Comment by th-otto** [comment]
I can add the changes to menu_popup(), just didn't want to do duplicate work.

> If anyone wants the items used for testing I can attach them (cpx/aes4demo).

Yes, that would be helpful. BTW, what AES version does N.AES report?

**Comment by lpgb** [comment]
N.AES reports AES 4.1
The demo also run in plain tos 4.04 and the submenus behave the same.

[aesdemo.zip](https://github.com/user-attachments/files/16143748/aesdemo.zip)
[submenu.zip](https://github.com/user-attachments/files/16143794/submenu.zip)

**Comment by lpgb** [comment]
Perhaps a small addition here as well.
https://freemint.github.io/tos.hyp/en/aes_structures.html#MN_SET

typedef struct
{
    int32_t display;    /* Submenu display delay             */
    int32_t drag;       /* Submenu drag delay                */
    int32_t delay;      /* Single-click scroll delay         */
    int32_t speed;     /* Continuous scroll delay           */
    int16_t height;     /* Popup scroll height (in items),   */
                       /* applied when _mn_scroll_ of [MENU](https://freemint.github.io/tos.hyp/en/aes_structures.html#MENU) is >0 */
} MN_SET;
