### ISSUE TITLE
XBIOS: Initmouse( ) wrong parameter description

### ISSUE THREAD

**Issue by DavidGZ** [freemint/tos.hyp#85]
From the Initmous() system call description it seems that in the parameter "mousevec" you can get the address of the mouse interrupt vector, but looking at the BIOS TOS sources (also in EmuTOS) the parameter is used to set the vector not to get it.

**Comment by th-otto** [comment]
Yes, the text is a bit misleading (also in german). mousevec is an input parameter only to set the address. It also fails to mention that the vector is not changed if the parameter is null.

**Comment by DavidGZ** [comment]
Regarding the behaviour when the parameter is null, I took a look in to the sources and it seems that only EmuTOS do this, I think TOS doesn't check if the parameter is null.

**Comment by mikrosk** [comment]
Yes, it seems TOS just sets whatever value has been passed in the vector parameter.
