### ISSUE TITLE
Devconnect() in fact does not return a value

### ISSUE THREAD

**Issue by mikrosk** [freemint/tos.hyp#91]
See https://github.com/freemint/freemint/issues/113 - in case of wrong `src` input parameter it returns zero (i.e. _not_ non-zero) but that is all, no further error checking nor setting d0 as an error code is done. Basically if it succeeds, it contains a random value which usually happens to be zero.

**Comment by th-otto** [comment]
See https://github.com/freemint/tos.hyp/blob/5a8cf43577b75d87e567478999a567c0b4b785e9/xbios/sound/devconne.ui#L60. It is already documented ;)

**Comment by mikrosk** [comment]
What is even better, it has been already published on https://freemint.github.io/tos.hyp/en/xbios_sound.html#devconnect. It totally forgot we'd done this. ;-) I should start using that URL (along with fixing stuff in https://github.com/freemint/tos.hyp/issues) from now on.

@pulsar122 do you have anything against making http://toshyp.atari.org backed by the github repository? For instance, http://powerphenix.com works [the same way](https://github.com/mikrosk/ct60tos/tree/gh-pages). I wouldn't be against transferring the whole repository to your ownership, as it is your work after all.
